### ISSUE TITLE
FYI: parallel() is ready, it could make resize notebook simpler

### ISSUE THREAD

**Issue by daisukelab** [radekosmulski/whale#5]
Hi,

Thank you for sharing notebooks. These notebooks help us so much, and we can spend more time for facing problem itself.

I found one small thing that might be useful for you. Please simply close this issue when you read, this is just for sharing with you.

This is about notebook `resize.ipynb`.

Fast.ai has a function `parallel` (please find in [fastai/core.py](https://github.com/fastai/fastai/blob/master/fastai/core.py)) which wraps ThreadPoolExecutor.

Then if you add extra parameter with `resize_img`,
```python
def resize_img(path, index):
    PIL.Image.open(path).resize((SZ,SZ), resample=PIL.Image.BICUBIC).save((PATH/f'{path.parent.name}-{SZ}'/path.name))
```

This will make it a little bit simpler:
```python
parallel(resize_img, files)
```

Just FYI.

**Comment by radekosmulski** [comment]
Happy to hear the notebooks are of use to you and thank you for the heads up that this exists, appreciate it! 

Will refactor to use `parallel` and will push an updated version. Might take me a while though as I am again experiencing issues with connecting to my deep learning rig due to ISP problems.

**Comment by radekosmulski** [comment]
switched to using `parallel` from `fastai`
